# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x12\n\x04\x64\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['data']
data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:data)
  })
_sym_db.RegisterMessage(data)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=14
  _DATA._serialized_end=32
# @@protoc_insertion_point(module_scope)
