# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrappedProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12wrappedProto.proto\"1\n\x06Person\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1a\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"Z\n\x0fTopLevelMessage\x12\x19\n\x06person\x18\x01 \x01(\x0b\x32\x07.PersonH\x00\x12\x1b\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x08.AddressH\x00\x42\x0f\n\rinner_messageb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_TOPLEVELMESSAGE = DESCRIPTOR.message_types_by_name['TopLevelMessage']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'wrappedProto_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'wrappedProto_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  })
_sym_db.RegisterMessage(Address)

TopLevelMessage = _reflection.GeneratedProtocolMessageType('TopLevelMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOPLEVELMESSAGE,
  '__module__' : 'wrappedProto_pb2'
  # @@protoc_insertion_point(class_scope:TopLevelMessage)
  })
_sym_db.RegisterMessage(TopLevelMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=22
  _PERSON._serialized_end=71
  _ADDRESS._serialized_start=73
  _ADDRESS._serialized_end=99
  _TOPLEVELMESSAGE._serialized_start=101
  _TOPLEVELMESSAGE._serialized_end=191
# @@protoc_insertion_point(module_scope)
