# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tcpModule import transmitter
from serdes import serializer
from xboxControl import XboxController
from threading import Thread
import time

class joyInitVals():
    Ix = 0
    Iy = 0
    IdigEnable = 0
    IdigAct = 0
    IdigVel = 0
    IdumpUP = 0
    IdumpDOWN = 0
    TrackdigEnable = 0
    estop = 0


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(20, 40, 801, 461))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Start = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.Start.setObjectName("Start")
        self.horizontalLayout_8.addWidget(self.Start)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.line_8 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_8.addWidget(self.line_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.line_13 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout.addWidget(self.line_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.dumpingACT = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.dumpingACT.setObjectName("dumpingACT")
        self.horizontalLayout_4.addWidget(self.dumpingACT)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(25, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.miningACT = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.miningACT.setObjectName("miningACT")
        self.horizontalLayout_2.addWidget(self.miningACT)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.miningMTR = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.miningMTR.setObjectName("miningMTR")
        self.horizontalLayout_6.addWidget(self.miningMTR)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem8 = QtWidgets.QSpacerItem(181, 69, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.xMTR = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.xMTR.setObjectName("xMTR")
        self.horizontalLayout.addWidget(self.xMTR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem9)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.yMTR = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.yMTR.setObjectName("yMTR")
        self.horizontalLayout_5.addWidget(self.yMTR)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_10 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line.setEnabled(True)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem12)
        self.line_12 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_4.addWidget(self.line_12)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem13 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.line_7 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.msgSent = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.msgSent.setObjectName("msgSent")
        self.horizontalLayout_3.addWidget(self.msgSent)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem15)
        self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.runtime = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.runtime.setObjectName("runtime")
        self.horizontalLayout_7.addWidget(self.runtime)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_11 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_4.addWidget(self.line_11)
        spacerItem17 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem17)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.line_9 = QtWidgets.QFrame(self.horizontalLayoutWidget_8)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_8.addWidget(self.line_9)
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #inheritance
        #class Student(Person):
        #class RMC(ui_mainwindow)
            #def __init__(self):
                #to refer to anything in the inherited class do:
                    #super().__init__ to run constructer of the superclass




        #addon
        self.Start.clicked.connect(self.run)
        self.xbox = XboxController()
        self.ser = serializer()
        #self.transmitter = transmitter()
        
        self.joyInitVals = joyInitVals()
        inputs = self.xbox.read()
        self.joyInitVals.Ix = inputs[0]
        self.joyInitVals.Iy = inputs[1]
        self.joyInitVals.IdigEnable = inputs[2]
        self.joyInitVals.IdigAct = inputs[3]
        self.joyInitVals.IdigVel = inputs[4]
        self.joyInitVals.IdumpUP = inputs[5]
        self.joyInitVals.IdumpDOWN = inputs[6]
        self.joyInitVals.estop = inputs[7]

    def run(self):

        #start the threads
        x = Thread(target=self.transmit)
        x.start()


    def transmit(self):
        while (True):
            self.process_joystick()
            time.sleep(.1)

    def updateUI(self):
        print(self.joyInitVals.Ix)
        self.xMTR.display(self.joyInitVals.Ix)
        self.yMTR.display(self.joyInitVals.Iy)
        self.miningMTR.display(self.joyInitVals.IdigVel)
        self.miningACT.display(self.joyInitVals.IdigAct)

        if self.joyInitVals.IdumpUP == 1:
            self.dumpingACT.display(1)
        elif self.joyInitVals.IdumpUP == 1:
            self.dumpingACT.display(-1)

    def process_joystick(self):
        #initialize inputs

        #controller inputs
        inputs = self.xbox.read()
        x           = inputs[0]
        y           = inputs[1]
        digEnable   = inputs[2]
        digAct      = inputs[3]
        digVel      = inputs[4]
        dumpUP      = inputs[5]
        dumpDOWN    = inputs[6]
        estop       = inputs[7]

        #Emergency Stop
        #if (estop == 1):
            #print('estop')
            #ser.updateMovement(0,0)
            #trans.send_msg(ser.serialize())
            #ser.updateMining(0, 0, 0, 0)
            #trans.send_msg(ser.serialize())
            #ser.updateDumping(0, 0)
            #trans.send_msg(ser.serialize())
            #continue


    #movement delta (delta can be used to adjust how much we want to sent)
        delta = 10
        if (abs(x-self.joyInitVals.Ix) > delta or abs(y-self.joyInitVals.Iy) > delta):
            print('x: ' + str(x) + ', y: ' + str(y))
            self.ser.updateMovement(y,x)
            #trans.send_msg(self.ser.serialize())
            self.joyInitVals.Ix = x
            self.joyInitVals.Iy = y
            self.updateUI()

    #digging deltas

        #digging enable/disable (actuators are not extending or retracting)
        if (digEnable == 1 and self.joyInitVals.IdigEnable != 1):
            if (self.joyInitVals.TrackdigEnable == 0):
                self.joyInitVals.TrackdigEnable = 1
            elif (self.joyInitVals.TrackdigEnable == 1):
                self.joyInitVals.TrackdigEnable = 0

            print('digEnable: ' + str(self.joyInitVals.TrackdigEnable))
            self.ser.updateMining(self.joyInitVals.TrackdigEnable, 0, 0, digVel)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdigEnable = 1

        elif (digEnable == 0):
            self.joyInitVals.IdigEnable = 0

        #digging actuator extend/retract: extend = 1, retract = 0
        if (digAct > 0 and digAct != self.joyInitVals.IdigAct):
            print('extendAct: ' + str(1))
            self.ser.updateMining(self.joyInitVals.TrackdigEnable, 1, 0, digVel)
            #trans.send_msg(ser.serialize()) #MAYBE MOVE TO THE END OF THE DIGGING SECTION?
            self.joyInitVals.IdigAct = digAct
            self.updateUI()
        elif (digAct < 0 and digAct != self.joyInitVals.IdigAct):
            print('retractAct: ' + str(-1))
            self.ser.updateMining(self.joyInitVals.TrackdigEnable, 0, 1, digVel)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdigAct = digAct
            self.updateUI()

        elif (digAct == 0 and digAct != self.joyInitVals.IdigAct):
            print('zeroAct: ' + str(0))
            self.ser.updateMining(self.joyInitVals.TrackdigEnable, 0, 0, digVel)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdigAct = digAct
            self.updateUI()

        #digging motor velocity
        delta = 10
        if (abs(digVel - self.joyInitVals.IdigVel) > delta):
            print('digVel:' + str(digVel))
            self.ser.updateMining(self.joyInitVals.TrackdigEnable, 0, 0, digVel)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdigVel = digVel

    #dumping delta
        if (dumpUP != self.joyInitVals.IdumpUP):
            print('dumpUp: ' + str(dumpUP))
            self.ser.updateDumping(dumpUP, 0)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdumpUP = dumpUP
        if (dumpDOWN != self.joyInitVals.IdumpDOWN):
            print('dumpDOWN: ' + str(dumpDOWN))
            self.ser.updateDumping(0, dumpDOWN)
            #trans.send_msg(ser.serialize())
            self.joyInitVals.IdumpDOWN = dumpDOWN

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Dumping ACT (extend/retract)"))
        self.label_5.setText(_translate("MainWindow", "Mining ACT (extend/retract)"))
        self.label_4.setText(_translate("MainWindow", "Mining MTR (forward/reverse)"))
        self.label_2.setText(_translate("MainWindow", "X (left/right)"))
        self.label_7.setText(_translate("MainWindow", "Y (forward/reverse)"))
        self.label.setText(_translate("MainWindow", "Connection Status"))
        self.label_3.setText(_translate("MainWindow", "# Messages Sent:"))
        self.label_8.setText(_translate("MainWindow", "System Runtime:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
