# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import person_info_pb2 as person__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x07persons\x1a\x11person_info.proto\"M\n\x06Person\x12!\n\x04info\x18\x01 \x01(\x0b\x32\x13.persons.PersonInfo\x12 \n\x07\x66riends\x18\x02 \x03(\x0b\x32\x0f.persons.Friend\"^\n\x06\x46riend\x12\x1b\n\x13\x66riendship_duration\x18\x01 \x01(\x02\x12\x16\n\x0eshared_hobbies\x18\x02 \x03(\t\x12\x1f\n\x06person\x18\x03 \x01(\x0b\x32\x0f.persons.Personb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_FRIEND = DESCRIPTOR.message_types_by_name['Friend']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:persons.Person)
  })
_sym_db.RegisterMessage(Person)

Friend = _reflection.GeneratedProtocolMessageType('Friend', (_message.Message,), {
  'DESCRIPTOR' : _FRIEND,
  '__module__' : 'person_pb2'
  # @@protoc_insertion_point(class_scope:persons.Friend)
  })
_sym_db.RegisterMessage(Friend)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=44
  _PERSON._serialized_end=121
  _FRIEND._serialized_start=123
  _FRIEND._serialized_end=217
# @@protoc_insertion_point(module_scope)
