# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11person_info.proto\x12\x07persons\"D\n\nPersonInfo\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x12\x19\n\x03sex\x18\x02 \x01(\x0e\x32\x0c.persons.Sex\x12\x0e\n\x06height\x18\x03 \x01(\x05*\x1a\n\x03Sex\x12\x05\n\x01M\x10\x00\x12\x05\n\x01\x46\x10\x01\x12\x05\n\x01O\x10\x02\x62\x06proto3')

_SEX = DESCRIPTOR.enum_types_by_name['Sex']
Sex = enum_type_wrapper.EnumTypeWrapper(_SEX)
M = 0
F = 1
O = 2


_PERSONINFO = DESCRIPTOR.message_types_by_name['PersonInfo']
PersonInfo = _reflection.GeneratedProtocolMessageType('PersonInfo', (_message.Message,), {
  'DESCRIPTOR' : _PERSONINFO,
  '__module__' : 'person_info_pb2'
  # @@protoc_insertion_point(class_scope:persons.PersonInfo)
  })
_sym_db.RegisterMessage(PersonInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEX._serialized_start=100
  _SEX._serialized_end=126
  _PERSONINFO._serialized_start=30
  _PERSONINFO._serialized_end=98
# @@protoc_insertion_point(module_scope)
