# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcmd.proto\",\n\x08Movement\x12\x0f\n\x07mtr_spd\x18\x01 \x01(\x05\x12\x0f\n\x07mtr_ang\x18\x02 \x01(\x05\"N\n\x06Mining\x12\x12\n\nmtr_mining\x18\x01 \x01(\x08\x12\x0e\n\x06\x65xtend\x18\x02 \x01(\x08\x12\x0f\n\x07retract\x18\x03 \x01(\x08\x12\x0f\n\x07\x64ig_spd\x18\x04 \x01(\r\"*\n\x07\x44umping\x12\x0e\n\x06\x65xtend\x18\x01 \x01(\x08\x12\x0f\n\x07retract\x18\x02 \x01(\x08\"n\n\x0eWrapperMessage\x12\x1d\n\x08movement\x18\x02 \x01(\x0b\x32\t.MovementH\x00\x12\x19\n\x06mining\x18\x03 \x01(\x0b\x32\x07.MiningH\x00\x12\x1b\n\x07\x64umping\x18\x04 \x01(\x0b\x32\x08.DumpingH\x00\x42\x05\n\x03msgb\x06proto3')



_MOVEMENT = DESCRIPTOR.message_types_by_name['Movement']
_MINING = DESCRIPTOR.message_types_by_name['Mining']
_DUMPING = DESCRIPTOR.message_types_by_name['Dumping']
_WRAPPERMESSAGE = DESCRIPTOR.message_types_by_name['WrapperMessage']
Movement = _reflection.GeneratedProtocolMessageType('Movement', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENT,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Movement)
  })
_sym_db.RegisterMessage(Movement)

Mining = _reflection.GeneratedProtocolMessageType('Mining', (_message.Message,), {
  'DESCRIPTOR' : _MINING,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Mining)
  })
_sym_db.RegisterMessage(Mining)

Dumping = _reflection.GeneratedProtocolMessageType('Dumping', (_message.Message,), {
  'DESCRIPTOR' : _DUMPING,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Dumping)
  })
_sym_db.RegisterMessage(Dumping)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERMESSAGE,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:WrapperMessage)
  })
_sym_db.RegisterMessage(WrapperMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVEMENT._serialized_start=13
  _MOVEMENT._serialized_end=57
  _MINING._serialized_start=59
  _MINING._serialized_end=137
  _DUMPING._serialized_start=139
  _DUMPING._serialized_end=181
  _WRAPPERMESSAGE._serialized_start=183
  _WRAPPERMESSAGE._serialized_end=293
# @@protoc_insertion_point(module_scope)
