# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcmd.proto\",\n\x08movement\x12\x0f\n\x07mtr_spd\x18\x01 \x01(\r\x12\x0f\n\x07mtr_ang\x18\x02 \x01(\r\"=\n\x06mining\x12\x12\n\nmtr_mining\x18\x01 \x01(\x08\x12\x0e\n\x06\x65xtend\x18\x02 \x01(\x08\x12\x0f\n\x07retract\x18\x03 \x01(\x08\"*\n\x07\x64umping\x12\x0e\n\x06\x65xtend\x18\x01 \x01(\x08\x12\x0f\n\x07retract\x18\x02 \x01(\x08\"t\n\x0eWrapperMessage\x12\x13\n\x0b\x63ommonField\x18\x01 \x01(\r\x12\x17\n\x02m1\x18\x02 \x01(\x0b\x32\t.movementH\x00\x12\x15\n\x02m2\x18\x03 \x01(\x0b\x32\x07.miningH\x00\x12\x16\n\x02m3\x18\x04 \x01(\x0b\x32\x08.dumpingH\x00\x42\x05\n\x03msgb\x06proto3')



_MOVEMENT = DESCRIPTOR.message_types_by_name['movement']
_MINING = DESCRIPTOR.message_types_by_name['mining']
_DUMPING = DESCRIPTOR.message_types_by_name['dumping']
_WRAPPERMESSAGE = DESCRIPTOR.message_types_by_name['WrapperMessage']
movement = _reflection.GeneratedProtocolMessageType('movement', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENT,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:movement)
  })
_sym_db.RegisterMessage(movement)

mining = _reflection.GeneratedProtocolMessageType('mining', (_message.Message,), {
  'DESCRIPTOR' : _MINING,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:mining)
  })
_sym_db.RegisterMessage(mining)

dumping = _reflection.GeneratedProtocolMessageType('dumping', (_message.Message,), {
  'DESCRIPTOR' : _DUMPING,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:dumping)
  })
_sym_db.RegisterMessage(dumping)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERMESSAGE,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:WrapperMessage)
  })
_sym_db.RegisterMessage(WrapperMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVEMENT._serialized_start=13
  _MOVEMENT._serialized_end=57
  _MINING._serialized_start=59
  _MINING._serialized_end=120
  _DUMPING._serialized_start=122
  _DUMPING._serialized_end=164
  _WRAPPERMESSAGE._serialized_start=166
  _WRAPPERMESSAGE._serialized_end=282
# @@protoc_insertion_point(module_scope)
